# The purpose of this workflow is to publish the wasmtime workspace of crates
# whenever a wasmtime tag is created. This baiscally boils down to running
# `scripts/publish.rs` at the right time.

name: "Publish to crates.io"

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    if: github.repository == 'bytecodealliance/wasmtime'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: |
        sha=${{ github.sha }}
        # Remember to update this logic in publish-artifacts.yml as well
        echo ARTIFACT_RUN_ID=$(
          gh api -H 'Accept: application/vnd.github+json' \
              /repos/${{ github.repository }}/actions/workflows/main.yml/runs\?exclude_pull_requests=true \
              | jq '.workflow_runs' \
              | jq "map(select(.head_commit.id == \"$sha\"))[0].id" \
        ) >> "$GITHUB_ENV"
    - run: rustup update stable && rustup default stable
    - run: |
        rustc scripts/publish.rs
        # ./publish publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    
    # Manifest and publish the wasi-preview1-component-adapter-provider
    - uses: actions/download-artifact@v4
      with:
        name: bins-wasi-preview1-component-adapter
        path: crates/wasi-preview1-component-adapter/provider/artefacts
        github-token: ${{ github.token }}
        run-id: ${ARTIFACT_RUN_ID}
    - run: ./ci/build-wasi-preview1-component-adapter-provider.sh
    - run: cargo publish -p wasi-preview1-component-adapter-provider --allow-dirty --dry-run
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
